apiVersion: skaffold/v4beta3
manifests:
  rawYaml:
    - ./infra/k8s/*

kind: Config
deploy:
  kubectl: {}
build:
  local:
    push: false
  artifacts:
    - image: client-service
      context: ./client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/*.js"
            dest: ./src
    - image: query-service
      context: ./query
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: posts-service
      context: ./posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: comments-service
      context: ./comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: moderation-service
      context: ./moderation
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .